include("C:/Program Files/CMake/share/cmake-4.4/Modules/GoogleTestAddTests.cmake")
gtest_discover_tests_impl(
  TEST_TARGET [==[tests]==]
  TEST_EXECUTABLE [==[C:/Users/jackl/Desktop/projects/Order Book V1/order-book-v1/src/build-clangd/tests.exe]==]
  TEST_EXECUTOR [==[]==]
  TEST_WORKING_DIR [==[C:/Users/jackl/Desktop/projects/Order Book V1/order-book-v1/src/build-clangd]==]
  TEST_EXTRA_ARGS [==[]==]
  TEST_PROPERTIES [==[]==]
  TEST_PREFIX [==[]==]
  TEST_SUFFIX [==[]==]
  TEST_FILTER [==[]==]
  NO_PRETTY_TYPES [==[FALSE]==]
  NO_PRETTY_VALUES [==[FALSE]==]
  TEST_LIST [==[tests_TESTS]==]
  CTEST_FILE [==[C:/Users/jackl/Desktop/projects/Order Book V1/order-book-v1/src/build-clangd/tests_e3b0c442_tests.cmake]==]
  TEST_DISCOVERY_TIMEOUT [==[5]==]
  TEST_DISCOVERY_EXTRA_ARGS [==[]==]
  TEST_XML_OUTPUT_DIR [==[]==]
  TEST_JSON_OUTPUT_DIR [==[C:/Users/jackl/Desktop/projects/Order Book V1/order-book-v1/src/build-clangd]==]
)
