if(EXISTS "/home/jackonick/code/order-book-v1/src/tests[1]_tests.cmake")
  include("/home/jackonick/code/order-book-v1/src/tests[1]_tests.cmake")
else()
  add_test(tests_NOT_BUILT tests_NOT_BUILT)
endif()
