// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: exchange.proto
#ifndef GRPC_exchange_2eproto__INCLUDED
#define GRPC_exchange_2eproto__INCLUDED

#include "exchange.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace exchange {

// ---- the service (replace your socket code) ----
class Exchange final {
 public:
  static constexpr char const* service_full_name() {
    return "exchange.Exchange";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::exchange::OrderResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>> AsyncSubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>>(AsyncSubmitOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>> PrepareAsyncSubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>>(PrepareAsyncSubmitOrderRaw(context, request, cq));
    }
    virtual ::grpc::Status SubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::exchange::CancelResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>> AsyncSubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>>(AsyncSubmitCancelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>> PrepareAsyncSubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>>(PrepareAsyncSubmitCancelRaw(context, request, cq));
    }
    virtual ::grpc::Status SubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::exchange::ModifyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::ModifyResponse>> AsyncSubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::ModifyResponse>>(AsyncSubmitModifyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::ModifyResponse>> PrepareAsyncSubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::ModifyResponse>>(PrepareAsyncSubmitModifyRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest* request, ::exchange::OrderResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest* request, ::exchange::OrderResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest* request, ::exchange::CancelResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest* request, ::exchange::CancelResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder* request, ::exchange::ModifyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder* request, ::exchange::ModifyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>* AsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>* PrepareAsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>* AsyncSubmitCancelRaw(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>* PrepareAsyncSubmitCancelRaw(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::ModifyResponse>* AsyncSubmitModifyRaw(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::ModifyResponse>* PrepareAsyncSubmitModifyRaw(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::exchange::OrderResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>> AsyncSubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>>(AsyncSubmitOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>> PrepareAsyncSubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>>(PrepareAsyncSubmitOrderRaw(context, request, cq));
    }
    ::grpc::Status SubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::exchange::CancelResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>> AsyncSubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>>(AsyncSubmitCancelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>> PrepareAsyncSubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>>(PrepareAsyncSubmitCancelRaw(context, request, cq));
    }
    ::grpc::Status SubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::exchange::ModifyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::ModifyResponse>> AsyncSubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::ModifyResponse>>(AsyncSubmitModifyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::ModifyResponse>> PrepareAsyncSubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::ModifyResponse>>(PrepareAsyncSubmitModifyRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest* request, ::exchange::OrderResponse* response, std::function<void(::grpc::Status)>) override;
      void SubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest* request, ::exchange::OrderResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest* request, ::exchange::CancelResponse* response, std::function<void(::grpc::Status)>) override;
      void SubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest* request, ::exchange::CancelResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder* request, ::exchange::ModifyResponse* response, std::function<void(::grpc::Status)>) override;
      void SubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder* request, ::exchange::ModifyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>* AsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>* PrepareAsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>* AsyncSubmitCancelRaw(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>* PrepareAsyncSubmitCancelRaw(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchange::ModifyResponse>* AsyncSubmitModifyRaw(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchange::ModifyResponse>* PrepareAsyncSubmitModifyRaw(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SubmitOrder_;
    const ::grpc::internal::RpcMethod rpcmethod_SubmitCancel_;
    const ::grpc::internal::RpcMethod rpcmethod_SubmitModify_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SubmitOrder(::grpc::ServerContext* context, const ::exchange::NewOrderRequest* request, ::exchange::OrderResponse* response);
    virtual ::grpc::Status SubmitCancel(::grpc::ServerContext* context, const ::exchange::NewCancelRequest* request, ::exchange::CancelResponse* response);
    virtual ::grpc::Status SubmitModify(::grpc::ServerContext* context, const ::exchange::NewModifyOrder* request, ::exchange::ModifyResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubmitOrder() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::NewOrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitOrder(::grpc::ServerContext* context, ::exchange::NewOrderRequest* request, ::grpc::ServerAsyncResponseWriter< ::exchange::OrderResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SubmitCancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubmitCancel() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SubmitCancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitCancel(::grpc::ServerContext* /*context*/, const ::exchange::NewCancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitCancel(::grpc::ServerContext* context, ::exchange::NewCancelRequest* request, ::grpc::ServerAsyncResponseWriter< ::exchange::CancelResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SubmitModify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubmitModify() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_SubmitModify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitModify(::grpc::ServerContext* /*context*/, const ::exchange::NewModifyOrder* /*request*/, ::exchange::ModifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitModify(::grpc::ServerContext* context, ::exchange::NewModifyOrder* request, ::grpc::ServerAsyncResponseWriter< ::exchange::ModifyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SubmitOrder<WithAsyncMethod_SubmitCancel<WithAsyncMethod_SubmitModify<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SubmitOrder() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::exchange::NewOrderRequest, ::exchange::OrderResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::exchange::NewOrderRequest* request, ::exchange::OrderResponse* response) { return this->SubmitOrder(context, request, response); }));}
    void SetMessageAllocatorFor_SubmitOrder(
        ::grpc::MessageAllocator< ::exchange::NewOrderRequest, ::exchange::OrderResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::exchange::NewOrderRequest, ::exchange::OrderResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::NewOrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::exchange::NewOrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SubmitCancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SubmitCancel() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::exchange::NewCancelRequest, ::exchange::CancelResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::exchange::NewCancelRequest* request, ::exchange::CancelResponse* response) { return this->SubmitCancel(context, request, response); }));}
    void SetMessageAllocatorFor_SubmitCancel(
        ::grpc::MessageAllocator< ::exchange::NewCancelRequest, ::exchange::CancelResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::exchange::NewCancelRequest, ::exchange::CancelResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SubmitCancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitCancel(::grpc::ServerContext* /*context*/, const ::exchange::NewCancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitCancel(
      ::grpc::CallbackServerContext* /*context*/, const ::exchange::NewCancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SubmitModify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SubmitModify() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::exchange::NewModifyOrder, ::exchange::ModifyResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::exchange::NewModifyOrder* request, ::exchange::ModifyResponse* response) { return this->SubmitModify(context, request, response); }));}
    void SetMessageAllocatorFor_SubmitModify(
        ::grpc::MessageAllocator< ::exchange::NewModifyOrder, ::exchange::ModifyResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::exchange::NewModifyOrder, ::exchange::ModifyResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SubmitModify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitModify(::grpc::ServerContext* /*context*/, const ::exchange::NewModifyOrder* /*request*/, ::exchange::ModifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitModify(
      ::grpc::CallbackServerContext* /*context*/, const ::exchange::NewModifyOrder* /*request*/, ::exchange::ModifyResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SubmitOrder<WithCallbackMethod_SubmitCancel<WithCallbackMethod_SubmitModify<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubmitOrder() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::NewOrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SubmitCancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubmitCancel() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SubmitCancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitCancel(::grpc::ServerContext* /*context*/, const ::exchange::NewCancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SubmitModify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubmitModify() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_SubmitModify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitModify(::grpc::ServerContext* /*context*/, const ::exchange::NewModifyOrder* /*request*/, ::exchange::ModifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubmitOrder() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::NewOrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitOrder(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubmitCancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubmitCancel() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SubmitCancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitCancel(::grpc::ServerContext* /*context*/, const ::exchange::NewCancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitCancel(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubmitModify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubmitModify() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_SubmitModify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitModify(::grpc::ServerContext* /*context*/, const ::exchange::NewModifyOrder* /*request*/, ::exchange::ModifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitModify(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SubmitOrder() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SubmitOrder(context, request, response); }));
    }
    ~WithRawCallbackMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::NewOrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SubmitCancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SubmitCancel() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SubmitCancel(context, request, response); }));
    }
    ~WithRawCallbackMethod_SubmitCancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitCancel(::grpc::ServerContext* /*context*/, const ::exchange::NewCancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitCancel(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SubmitModify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SubmitModify() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SubmitModify(context, request, response); }));
    }
    ~WithRawCallbackMethod_SubmitModify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitModify(::grpc::ServerContext* /*context*/, const ::exchange::NewModifyOrder* /*request*/, ::exchange::ModifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitModify(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SubmitOrder() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::exchange::NewOrderRequest, ::exchange::OrderResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::exchange::NewOrderRequest, ::exchange::OrderResponse>* streamer) {
                       return this->StreamedSubmitOrder(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::NewOrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubmitOrder(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::exchange::NewOrderRequest,::exchange::OrderResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubmitCancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SubmitCancel() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::exchange::NewCancelRequest, ::exchange::CancelResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::exchange::NewCancelRequest, ::exchange::CancelResponse>* streamer) {
                       return this->StreamedSubmitCancel(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SubmitCancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubmitCancel(::grpc::ServerContext* /*context*/, const ::exchange::NewCancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubmitCancel(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::exchange::NewCancelRequest,::exchange::CancelResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubmitModify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SubmitModify() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::exchange::NewModifyOrder, ::exchange::ModifyResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::exchange::NewModifyOrder, ::exchange::ModifyResponse>* streamer) {
                       return this->StreamedSubmitModify(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SubmitModify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubmitModify(::grpc::ServerContext* /*context*/, const ::exchange::NewModifyOrder* /*request*/, ::exchange::ModifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubmitModify(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::exchange::NewModifyOrder,::exchange::ModifyResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SubmitOrder<WithStreamedUnaryMethod_SubmitCancel<WithStreamedUnaryMethod_SubmitModify<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SubmitOrder<WithStreamedUnaryMethod_SubmitCancel<WithStreamedUnaryMethod_SubmitModify<Service > > > StreamedService;
};

}  // namespace exchange


#endif  // GRPC_exchange_2eproto__INCLUDED
