// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_exchange_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_exchange_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_exchange_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_exchange_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_exchange_2eproto;
namespace exchange {
class CancelResponse;
struct CancelResponseDefaultTypeInternal;
extern CancelResponseDefaultTypeInternal _CancelResponse_default_instance_;
class ModifyResponse;
struct ModifyResponseDefaultTypeInternal;
extern ModifyResponseDefaultTypeInternal _ModifyResponse_default_instance_;
class NewCancelRequest;
struct NewCancelRequestDefaultTypeInternal;
extern NewCancelRequestDefaultTypeInternal _NewCancelRequest_default_instance_;
class NewModifyOrder;
struct NewModifyOrderDefaultTypeInternal;
extern NewModifyOrderDefaultTypeInternal _NewModifyOrder_default_instance_;
class NewOrderRequest;
struct NewOrderRequestDefaultTypeInternal;
extern NewOrderRequestDefaultTypeInternal _NewOrderRequest_default_instance_;
class OrderResponse;
struct OrderResponseDefaultTypeInternal;
extern OrderResponseDefaultTypeInternal _OrderResponse_default_instance_;
}  // namespace exchange
PROTOBUF_NAMESPACE_OPEN
template<> ::exchange::CancelResponse* Arena::CreateMaybeMessage<::exchange::CancelResponse>(Arena*);
template<> ::exchange::ModifyResponse* Arena::CreateMaybeMessage<::exchange::ModifyResponse>(Arena*);
template<> ::exchange::NewCancelRequest* Arena::CreateMaybeMessage<::exchange::NewCancelRequest>(Arena*);
template<> ::exchange::NewModifyOrder* Arena::CreateMaybeMessage<::exchange::NewModifyOrder>(Arena*);
template<> ::exchange::NewOrderRequest* Arena::CreateMaybeMessage<::exchange::NewOrderRequest>(Arena*);
template<> ::exchange::OrderResponse* Arena::CreateMaybeMessage<::exchange::OrderResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace exchange {

// ===================================================================

class NewOrderRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.NewOrderRequest) */ {
 public:
  inline NewOrderRequest() : NewOrderRequest(nullptr) {}
  ~NewOrderRequest() override;
  explicit constexpr NewOrderRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NewOrderRequest(const NewOrderRequest& from);
  NewOrderRequest(NewOrderRequest&& from) noexcept
    : NewOrderRequest() {
    *this = ::std::move(from);
  }

  inline NewOrderRequest& operator=(const NewOrderRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline NewOrderRequest& operator=(NewOrderRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NewOrderRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const NewOrderRequest* internal_default_instance() {
    return reinterpret_cast<const NewOrderRequest*>(
               &_NewOrderRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NewOrderRequest& a, NewOrderRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(NewOrderRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NewOrderRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NewOrderRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NewOrderRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NewOrderRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const NewOrderRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NewOrderRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.NewOrderRequest";
  }
  protected:
  explicit NewOrderRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSideFieldNumber = 1,
    kOrderTypeFieldNumber = 2,
    kPriceFieldNumber = 3,
    kSizeFieldNumber = 4,
    kReserveFieldNumber = 5,
    kDisplaySizeFieldNumber = 6,
  };
  // uint32 side = 1;
  void clear_side();
  uint32_t side() const;
  void set_side(uint32_t value);
  private:
  uint32_t _internal_side() const;
  void _internal_set_side(uint32_t value);
  public:

  // uint32 order_type = 2;
  void clear_order_type();
  uint32_t order_type() const;
  void set_order_type(uint32_t value);
  private:
  uint32_t _internal_order_type() const;
  void _internal_set_order_type(uint32_t value);
  public:

  // uint64 price = 3;
  void clear_price();
  uint64_t price() const;
  void set_price(uint64_t value);
  private:
  uint64_t _internal_price() const;
  void _internal_set_price(uint64_t value);
  public:

  // uint64 size = 4;
  void clear_size();
  uint64_t size() const;
  void set_size(uint64_t value);
  private:
  uint64_t _internal_size() const;
  void _internal_set_size(uint64_t value);
  public:

  // uint64 reserve = 5;
  void clear_reserve();
  uint64_t reserve() const;
  void set_reserve(uint64_t value);
  private:
  uint64_t _internal_reserve() const;
  void _internal_set_reserve(uint64_t value);
  public:

  // uint64 display_size = 6;
  void clear_display_size();
  uint64_t display_size() const;
  void set_display_size(uint64_t value);
  private:
  uint64_t _internal_display_size() const;
  void _internal_set_display_size(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.NewOrderRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t side_;
  uint32_t order_type_;
  uint64_t price_;
  uint64_t size_;
  uint64_t reserve_;
  uint64_t display_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class OrderResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.OrderResponse) */ {
 public:
  inline OrderResponse() : OrderResponse(nullptr) {}
  ~OrderResponse() override;
  explicit constexpr OrderResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OrderResponse(const OrderResponse& from);
  OrderResponse(OrderResponse&& from) noexcept
    : OrderResponse() {
    *this = ::std::move(from);
  }

  inline OrderResponse& operator=(const OrderResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline OrderResponse& operator=(OrderResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OrderResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const OrderResponse* internal_default_instance() {
    return reinterpret_cast<const OrderResponse*>(
               &_OrderResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(OrderResponse& a, OrderResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(OrderResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OrderResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OrderResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OrderResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OrderResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const OrderResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OrderResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.OrderResponse";
  }
  protected:
  explicit OrderResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAssignedIdFieldNumber = 1,
    kFilledSizeFieldNumber = 3,
    kAcceptedFieldNumber = 2,
    kReasonFieldNumber = 4,
  };
  // uint64 assigned_id = 1;
  void clear_assigned_id();
  uint64_t assigned_id() const;
  void set_assigned_id(uint64_t value);
  private:
  uint64_t _internal_assigned_id() const;
  void _internal_set_assigned_id(uint64_t value);
  public:

  // uint64 filled_size = 3;
  void clear_filled_size();
  uint64_t filled_size() const;
  void set_filled_size(uint64_t value);
  private:
  uint64_t _internal_filled_size() const;
  void _internal_set_filled_size(uint64_t value);
  public:

  // bool accepted = 2;
  void clear_accepted();
  bool accepted() const;
  void set_accepted(bool value);
  private:
  bool _internal_accepted() const;
  void _internal_set_accepted(bool value);
  public:

  // uint32 reason = 4;
  void clear_reason();
  uint32_t reason() const;
  void set_reason(uint32_t value);
  private:
  uint32_t _internal_reason() const;
  void _internal_set_reason(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.OrderResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint64_t assigned_id_;
  uint64_t filled_size_;
  bool accepted_;
  uint32_t reason_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class NewCancelRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.NewCancelRequest) */ {
 public:
  inline NewCancelRequest() : NewCancelRequest(nullptr) {}
  ~NewCancelRequest() override;
  explicit constexpr NewCancelRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NewCancelRequest(const NewCancelRequest& from);
  NewCancelRequest(NewCancelRequest&& from) noexcept
    : NewCancelRequest() {
    *this = ::std::move(from);
  }

  inline NewCancelRequest& operator=(const NewCancelRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline NewCancelRequest& operator=(NewCancelRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NewCancelRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const NewCancelRequest* internal_default_instance() {
    return reinterpret_cast<const NewCancelRequest*>(
               &_NewCancelRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(NewCancelRequest& a, NewCancelRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(NewCancelRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NewCancelRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NewCancelRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NewCancelRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NewCancelRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const NewCancelRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NewCancelRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.NewCancelRequest";
  }
  protected:
  explicit NewCancelRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.NewCancelRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint64_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class CancelResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.CancelResponse) */ {
 public:
  inline CancelResponse() : CancelResponse(nullptr) {}
  ~CancelResponse() override;
  explicit constexpr CancelResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CancelResponse(const CancelResponse& from);
  CancelResponse(CancelResponse&& from) noexcept
    : CancelResponse() {
    *this = ::std::move(from);
  }

  inline CancelResponse& operator=(const CancelResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CancelResponse& operator=(CancelResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CancelResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const CancelResponse* internal_default_instance() {
    return reinterpret_cast<const CancelResponse*>(
               &_CancelResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CancelResponse& a, CancelResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(CancelResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CancelResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CancelResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CancelResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CancelResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CancelResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CancelResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.CancelResponse";
  }
  protected:
  explicit CancelResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReasonFieldNumber = 1,
  };
  // uint32 reason = 1;
  void clear_reason();
  uint32_t reason() const;
  void set_reason(uint32_t value);
  private:
  uint32_t _internal_reason() const;
  void _internal_set_reason(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.CancelResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t reason_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class NewModifyOrder final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.NewModifyOrder) */ {
 public:
  inline NewModifyOrder() : NewModifyOrder(nullptr) {}
  ~NewModifyOrder() override;
  explicit constexpr NewModifyOrder(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NewModifyOrder(const NewModifyOrder& from);
  NewModifyOrder(NewModifyOrder&& from) noexcept
    : NewModifyOrder() {
    *this = ::std::move(from);
  }

  inline NewModifyOrder& operator=(const NewModifyOrder& from) {
    CopyFrom(from);
    return *this;
  }
  inline NewModifyOrder& operator=(NewModifyOrder&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NewModifyOrder& default_instance() {
    return *internal_default_instance();
  }
  static inline const NewModifyOrder* internal_default_instance() {
    return reinterpret_cast<const NewModifyOrder*>(
               &_NewModifyOrder_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(NewModifyOrder& a, NewModifyOrder& b) {
    a.Swap(&b);
  }
  inline void Swap(NewModifyOrder* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NewModifyOrder* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NewModifyOrder* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NewModifyOrder>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NewModifyOrder& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const NewModifyOrder& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NewModifyOrder* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.NewModifyOrder";
  }
  protected:
  explicit NewModifyOrder(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kPriceFieldNumber = 2,
    kSizeFieldNumber = 3,
  };
  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // optional uint64 price = 2;
  bool has_price() const;
  private:
  bool _internal_has_price() const;
  public:
  void clear_price();
  uint64_t price() const;
  void set_price(uint64_t value);
  private:
  uint64_t _internal_price() const;
  void _internal_set_price(uint64_t value);
  public:

  // optional uint64 size = 3;
  bool has_size() const;
  private:
  bool _internal_has_size() const;
  public:
  void clear_size();
  uint64_t size() const;
  void set_size(uint64_t value);
  private:
  uint64_t _internal_size() const;
  void _internal_set_size(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.NewModifyOrder)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint64_t id_;
  uint64_t price_;
  uint64_t size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class ModifyResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.ModifyResponse) */ {
 public:
  inline ModifyResponse() : ModifyResponse(nullptr) {}
  ~ModifyResponse() override;
  explicit constexpr ModifyResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ModifyResponse(const ModifyResponse& from);
  ModifyResponse(ModifyResponse&& from) noexcept
    : ModifyResponse() {
    *this = ::std::move(from);
  }

  inline ModifyResponse& operator=(const ModifyResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModifyResponse& operator=(ModifyResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModifyResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModifyResponse* internal_default_instance() {
    return reinterpret_cast<const ModifyResponse*>(
               &_ModifyResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ModifyResponse& a, ModifyResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ModifyResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModifyResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModifyResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ModifyResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ModifyResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ModifyResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModifyResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.ModifyResponse";
  }
  protected:
  explicit ModifyResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReasonFieldNumber = 1,
    kAcceptedFieldNumber = 2,
    kIdFieldNumber = 3,
  };
  // uint32 reason = 1;
  void clear_reason();
  uint32_t reason() const;
  void set_reason(uint32_t value);
  private:
  uint32_t _internal_reason() const;
  void _internal_set_reason(uint32_t value);
  public:

  // bool accepted = 2;
  void clear_accepted();
  bool accepted() const;
  void set_accepted(bool value);
  private:
  bool _internal_accepted() const;
  void _internal_set_accepted(bool value);
  public:

  // uint64 id = 3;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.ModifyResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t reason_;
  bool accepted_;
  uint64_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NewOrderRequest

// uint32 side = 1;
inline void NewOrderRequest::clear_side() {
  side_ = 0u;
}
inline uint32_t NewOrderRequest::_internal_side() const {
  return side_;
}
inline uint32_t NewOrderRequest::side() const {
  // @@protoc_insertion_point(field_get:exchange.NewOrderRequest.side)
  return _internal_side();
}
inline void NewOrderRequest::_internal_set_side(uint32_t value) {
  
  side_ = value;
}
inline void NewOrderRequest::set_side(uint32_t value) {
  _internal_set_side(value);
  // @@protoc_insertion_point(field_set:exchange.NewOrderRequest.side)
}

// uint32 order_type = 2;
inline void NewOrderRequest::clear_order_type() {
  order_type_ = 0u;
}
inline uint32_t NewOrderRequest::_internal_order_type() const {
  return order_type_;
}
inline uint32_t NewOrderRequest::order_type() const {
  // @@protoc_insertion_point(field_get:exchange.NewOrderRequest.order_type)
  return _internal_order_type();
}
inline void NewOrderRequest::_internal_set_order_type(uint32_t value) {
  
  order_type_ = value;
}
inline void NewOrderRequest::set_order_type(uint32_t value) {
  _internal_set_order_type(value);
  // @@protoc_insertion_point(field_set:exchange.NewOrderRequest.order_type)
}

// uint64 price = 3;
inline void NewOrderRequest::clear_price() {
  price_ = uint64_t{0u};
}
inline uint64_t NewOrderRequest::_internal_price() const {
  return price_;
}
inline uint64_t NewOrderRequest::price() const {
  // @@protoc_insertion_point(field_get:exchange.NewOrderRequest.price)
  return _internal_price();
}
inline void NewOrderRequest::_internal_set_price(uint64_t value) {
  
  price_ = value;
}
inline void NewOrderRequest::set_price(uint64_t value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:exchange.NewOrderRequest.price)
}

// uint64 size = 4;
inline void NewOrderRequest::clear_size() {
  size_ = uint64_t{0u};
}
inline uint64_t NewOrderRequest::_internal_size() const {
  return size_;
}
inline uint64_t NewOrderRequest::size() const {
  // @@protoc_insertion_point(field_get:exchange.NewOrderRequest.size)
  return _internal_size();
}
inline void NewOrderRequest::_internal_set_size(uint64_t value) {
  
  size_ = value;
}
inline void NewOrderRequest::set_size(uint64_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:exchange.NewOrderRequest.size)
}

// uint64 reserve = 5;
inline void NewOrderRequest::clear_reserve() {
  reserve_ = uint64_t{0u};
}
inline uint64_t NewOrderRequest::_internal_reserve() const {
  return reserve_;
}
inline uint64_t NewOrderRequest::reserve() const {
  // @@protoc_insertion_point(field_get:exchange.NewOrderRequest.reserve)
  return _internal_reserve();
}
inline void NewOrderRequest::_internal_set_reserve(uint64_t value) {
  
  reserve_ = value;
}
inline void NewOrderRequest::set_reserve(uint64_t value) {
  _internal_set_reserve(value);
  // @@protoc_insertion_point(field_set:exchange.NewOrderRequest.reserve)
}

// uint64 display_size = 6;
inline void NewOrderRequest::clear_display_size() {
  display_size_ = uint64_t{0u};
}
inline uint64_t NewOrderRequest::_internal_display_size() const {
  return display_size_;
}
inline uint64_t NewOrderRequest::display_size() const {
  // @@protoc_insertion_point(field_get:exchange.NewOrderRequest.display_size)
  return _internal_display_size();
}
inline void NewOrderRequest::_internal_set_display_size(uint64_t value) {
  
  display_size_ = value;
}
inline void NewOrderRequest::set_display_size(uint64_t value) {
  _internal_set_display_size(value);
  // @@protoc_insertion_point(field_set:exchange.NewOrderRequest.display_size)
}

// -------------------------------------------------------------------

// OrderResponse

// uint64 assigned_id = 1;
inline void OrderResponse::clear_assigned_id() {
  assigned_id_ = uint64_t{0u};
}
inline uint64_t OrderResponse::_internal_assigned_id() const {
  return assigned_id_;
}
inline uint64_t OrderResponse::assigned_id() const {
  // @@protoc_insertion_point(field_get:exchange.OrderResponse.assigned_id)
  return _internal_assigned_id();
}
inline void OrderResponse::_internal_set_assigned_id(uint64_t value) {
  
  assigned_id_ = value;
}
inline void OrderResponse::set_assigned_id(uint64_t value) {
  _internal_set_assigned_id(value);
  // @@protoc_insertion_point(field_set:exchange.OrderResponse.assigned_id)
}

// bool accepted = 2;
inline void OrderResponse::clear_accepted() {
  accepted_ = false;
}
inline bool OrderResponse::_internal_accepted() const {
  return accepted_;
}
inline bool OrderResponse::accepted() const {
  // @@protoc_insertion_point(field_get:exchange.OrderResponse.accepted)
  return _internal_accepted();
}
inline void OrderResponse::_internal_set_accepted(bool value) {
  
  accepted_ = value;
}
inline void OrderResponse::set_accepted(bool value) {
  _internal_set_accepted(value);
  // @@protoc_insertion_point(field_set:exchange.OrderResponse.accepted)
}

// uint64 filled_size = 3;
inline void OrderResponse::clear_filled_size() {
  filled_size_ = uint64_t{0u};
}
inline uint64_t OrderResponse::_internal_filled_size() const {
  return filled_size_;
}
inline uint64_t OrderResponse::filled_size() const {
  // @@protoc_insertion_point(field_get:exchange.OrderResponse.filled_size)
  return _internal_filled_size();
}
inline void OrderResponse::_internal_set_filled_size(uint64_t value) {
  
  filled_size_ = value;
}
inline void OrderResponse::set_filled_size(uint64_t value) {
  _internal_set_filled_size(value);
  // @@protoc_insertion_point(field_set:exchange.OrderResponse.filled_size)
}

// uint32 reason = 4;
inline void OrderResponse::clear_reason() {
  reason_ = 0u;
}
inline uint32_t OrderResponse::_internal_reason() const {
  return reason_;
}
inline uint32_t OrderResponse::reason() const {
  // @@protoc_insertion_point(field_get:exchange.OrderResponse.reason)
  return _internal_reason();
}
inline void OrderResponse::_internal_set_reason(uint32_t value) {
  
  reason_ = value;
}
inline void OrderResponse::set_reason(uint32_t value) {
  _internal_set_reason(value);
  // @@protoc_insertion_point(field_set:exchange.OrderResponse.reason)
}

// -------------------------------------------------------------------

// NewCancelRequest

// uint64 id = 1;
inline void NewCancelRequest::clear_id() {
  id_ = uint64_t{0u};
}
inline uint64_t NewCancelRequest::_internal_id() const {
  return id_;
}
inline uint64_t NewCancelRequest::id() const {
  // @@protoc_insertion_point(field_get:exchange.NewCancelRequest.id)
  return _internal_id();
}
inline void NewCancelRequest::_internal_set_id(uint64_t value) {
  
  id_ = value;
}
inline void NewCancelRequest::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:exchange.NewCancelRequest.id)
}

// -------------------------------------------------------------------

// CancelResponse

// uint32 reason = 1;
inline void CancelResponse::clear_reason() {
  reason_ = 0u;
}
inline uint32_t CancelResponse::_internal_reason() const {
  return reason_;
}
inline uint32_t CancelResponse::reason() const {
  // @@protoc_insertion_point(field_get:exchange.CancelResponse.reason)
  return _internal_reason();
}
inline void CancelResponse::_internal_set_reason(uint32_t value) {
  
  reason_ = value;
}
inline void CancelResponse::set_reason(uint32_t value) {
  _internal_set_reason(value);
  // @@protoc_insertion_point(field_set:exchange.CancelResponse.reason)
}

// -------------------------------------------------------------------

// NewModifyOrder

// uint64 id = 1;
inline void NewModifyOrder::clear_id() {
  id_ = uint64_t{0u};
}
inline uint64_t NewModifyOrder::_internal_id() const {
  return id_;
}
inline uint64_t NewModifyOrder::id() const {
  // @@protoc_insertion_point(field_get:exchange.NewModifyOrder.id)
  return _internal_id();
}
inline void NewModifyOrder::_internal_set_id(uint64_t value) {
  
  id_ = value;
}
inline void NewModifyOrder::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:exchange.NewModifyOrder.id)
}

// optional uint64 price = 2;
inline bool NewModifyOrder::_internal_has_price() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool NewModifyOrder::has_price() const {
  return _internal_has_price();
}
inline void NewModifyOrder::clear_price() {
  price_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000001u;
}
inline uint64_t NewModifyOrder::_internal_price() const {
  return price_;
}
inline uint64_t NewModifyOrder::price() const {
  // @@protoc_insertion_point(field_get:exchange.NewModifyOrder.price)
  return _internal_price();
}
inline void NewModifyOrder::_internal_set_price(uint64_t value) {
  _has_bits_[0] |= 0x00000001u;
  price_ = value;
}
inline void NewModifyOrder::set_price(uint64_t value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:exchange.NewModifyOrder.price)
}

// optional uint64 size = 3;
inline bool NewModifyOrder::_internal_has_size() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool NewModifyOrder::has_size() const {
  return _internal_has_size();
}
inline void NewModifyOrder::clear_size() {
  size_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000002u;
}
inline uint64_t NewModifyOrder::_internal_size() const {
  return size_;
}
inline uint64_t NewModifyOrder::size() const {
  // @@protoc_insertion_point(field_get:exchange.NewModifyOrder.size)
  return _internal_size();
}
inline void NewModifyOrder::_internal_set_size(uint64_t value) {
  _has_bits_[0] |= 0x00000002u;
  size_ = value;
}
inline void NewModifyOrder::set_size(uint64_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:exchange.NewModifyOrder.size)
}

// -------------------------------------------------------------------

// ModifyResponse

// uint32 reason = 1;
inline void ModifyResponse::clear_reason() {
  reason_ = 0u;
}
inline uint32_t ModifyResponse::_internal_reason() const {
  return reason_;
}
inline uint32_t ModifyResponse::reason() const {
  // @@protoc_insertion_point(field_get:exchange.ModifyResponse.reason)
  return _internal_reason();
}
inline void ModifyResponse::_internal_set_reason(uint32_t value) {
  
  reason_ = value;
}
inline void ModifyResponse::set_reason(uint32_t value) {
  _internal_set_reason(value);
  // @@protoc_insertion_point(field_set:exchange.ModifyResponse.reason)
}

// bool accepted = 2;
inline void ModifyResponse::clear_accepted() {
  accepted_ = false;
}
inline bool ModifyResponse::_internal_accepted() const {
  return accepted_;
}
inline bool ModifyResponse::accepted() const {
  // @@protoc_insertion_point(field_get:exchange.ModifyResponse.accepted)
  return _internal_accepted();
}
inline void ModifyResponse::_internal_set_accepted(bool value) {
  
  accepted_ = value;
}
inline void ModifyResponse::set_accepted(bool value) {
  _internal_set_accepted(value);
  // @@protoc_insertion_point(field_set:exchange.ModifyResponse.accepted)
}

// uint64 id = 3;
inline void ModifyResponse::clear_id() {
  id_ = uint64_t{0u};
}
inline uint64_t ModifyResponse::_internal_id() const {
  return id_;
}
inline uint64_t ModifyResponse::id() const {
  // @@protoc_insertion_point(field_get:exchange.ModifyResponse.id)
  return _internal_id();
}
inline void ModifyResponse::_internal_set_id(uint64_t value) {
  
  id_ = value;
}
inline void ModifyResponse::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:exchange.ModifyResponse.id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace exchange

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_exchange_2eproto
