// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: exchange.proto

#include "exchange.pb.h"
#include "exchange.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace exchange {

static const char* Exchange_method_names[] = {
  "/exchange.Exchange/SubmitOrder",
  "/exchange.Exchange/SubmitCancel",
  "/exchange.Exchange/SubmitModify",
};

std::unique_ptr< Exchange::Stub> Exchange::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Exchange::Stub> stub(new Exchange::Stub(channel, options));
  return stub;
}

Exchange::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SubmitOrder_(Exchange_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SubmitCancel_(Exchange_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SubmitModify_(Exchange_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Exchange::Stub::SubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::exchange::OrderResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::exchange::NewOrderRequest, ::exchange::OrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SubmitOrder_, context, request, response);
}

void Exchange::Stub::async::SubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest* request, ::exchange::OrderResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::exchange::NewOrderRequest, ::exchange::OrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitOrder_, context, request, response, std::move(f));
}

void Exchange::Stub::async::SubmitOrder(::grpc::ClientContext* context, const ::exchange::NewOrderRequest* request, ::exchange::OrderResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>* Exchange::Stub::PrepareAsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::exchange::OrderResponse, ::exchange::NewOrderRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SubmitOrder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>* Exchange::Stub::AsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::NewOrderRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubmitOrderRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Exchange::Stub::SubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::exchange::CancelResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::exchange::NewCancelRequest, ::exchange::CancelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SubmitCancel_, context, request, response);
}

void Exchange::Stub::async::SubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest* request, ::exchange::CancelResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::exchange::NewCancelRequest, ::exchange::CancelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitCancel_, context, request, response, std::move(f));
}

void Exchange::Stub::async::SubmitCancel(::grpc::ClientContext* context, const ::exchange::NewCancelRequest* request, ::exchange::CancelResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitCancel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>* Exchange::Stub::PrepareAsyncSubmitCancelRaw(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::exchange::CancelResponse, ::exchange::NewCancelRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SubmitCancel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>* Exchange::Stub::AsyncSubmitCancelRaw(::grpc::ClientContext* context, const ::exchange::NewCancelRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubmitCancelRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Exchange::Stub::SubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::exchange::ModifyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::exchange::NewModifyOrder, ::exchange::ModifyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SubmitModify_, context, request, response);
}

void Exchange::Stub::async::SubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder* request, ::exchange::ModifyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::exchange::NewModifyOrder, ::exchange::ModifyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitModify_, context, request, response, std::move(f));
}

void Exchange::Stub::async::SubmitModify(::grpc::ClientContext* context, const ::exchange::NewModifyOrder* request, ::exchange::ModifyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitModify_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::exchange::ModifyResponse>* Exchange::Stub::PrepareAsyncSubmitModifyRaw(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::exchange::ModifyResponse, ::exchange::NewModifyOrder, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SubmitModify_, context, request);
}

::grpc::ClientAsyncResponseReader< ::exchange::ModifyResponse>* Exchange::Stub::AsyncSubmitModifyRaw(::grpc::ClientContext* context, const ::exchange::NewModifyOrder& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubmitModifyRaw(context, request, cq);
  result->StartCall();
  return result;
}

Exchange::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Exchange_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Exchange::Service, ::exchange::NewOrderRequest, ::exchange::OrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Exchange::Service* service,
             ::grpc::ServerContext* ctx,
             const ::exchange::NewOrderRequest* req,
             ::exchange::OrderResponse* resp) {
               return service->SubmitOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Exchange_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Exchange::Service, ::exchange::NewCancelRequest, ::exchange::CancelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Exchange::Service* service,
             ::grpc::ServerContext* ctx,
             const ::exchange::NewCancelRequest* req,
             ::exchange::CancelResponse* resp) {
               return service->SubmitCancel(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Exchange_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Exchange::Service, ::exchange::NewModifyOrder, ::exchange::ModifyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Exchange::Service* service,
             ::grpc::ServerContext* ctx,
             const ::exchange::NewModifyOrder* req,
             ::exchange::ModifyResponse* resp) {
               return service->SubmitModify(ctx, req, resp);
             }, this)));
}

Exchange::Service::~Service() {
}

::grpc::Status Exchange::Service::SubmitOrder(::grpc::ServerContext* context, const ::exchange::NewOrderRequest* request, ::exchange::OrderResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Exchange::Service::SubmitCancel(::grpc::ServerContext* context, const ::exchange::NewCancelRequest* request, ::exchange::CancelResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Exchange::Service::SubmitModify(::grpc::ServerContext* context, const ::exchange::NewModifyOrder* request, ::exchange::ModifyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace exchange

